[build]
image = "python"
command = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn pizza.wsgi"

[deploy]
branch = "master"

[engine]
node = "16.x"

[[environments]]
name = 'production'

[[environments.variables]]
key = 'i0&iq&e9u9h6(4_7%pt2s9)f=c$kso=k$c$w@fi9215s=1q0^d'
